### ISSUE TITLE
rhobetaepsilon.com redirects to destinationdomain.com

### ISSUE THREAD

**Issue by alextac98** [RhoBetaEpsilonWPI/Websites#1]

**Comment by arthurlockman** [comment]
FYI, the old domain name was rhobetaepsilon.org. It looks like that redirects to some random site too.

**Comment by alextac98** [comment]
> FYI, the old domain name was rhobetaepsilon.org. It looks like that redirects to some random site too.

Yes, we lost that domain, so we have switched to rhobetaepsilon.com. I am keeping a lookout to potentially get it next year so we have both

**Comment by alextac98** [comment]
Seems like this was a DNS issue, and has fixed itself. Reopen if the issue comes back again
